/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#ff6b00',
        'on-primary-fixed': '#351000',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed-variant': '#474646',
        'on-primary-fixed-variant': '#7a3000',
        'surface': '#0e1416',
        'tertiary-fixed-dim': '#c8c6c5',
        'error': '#ffb4ab',
        'on-secondary-container': '#bab8b7',
        'surface-bright': '#333a3c',
        'tertiary-fixed': '#e5e2e1',
        'on-error': '#690005',
        'inverse-on-surface': '#2b3234',
        'surface-container-lowest': '#080f11',
        'on-tertiary': '#313030',
        'surface-tint': '#ffb693',
        'secondary-fixed': '#e5e2e1',
        'on-secondary': '#313030',
        'secondary-container': '#4a4949',
        'on-surface': '#dde4e6',
        'on-primary-container': '#572000',
        'on-tertiary-fixed-variant': '#474746',
        'on-tertiary-container': '#313131',
        'surface-container': '#1a2123',
        'on-background': '#dde4e6',
        'tertiary-container': '#9a9898',
        'surface-dim': '#0e1416',
        'on-primary': '#561f00',
        'surface-variant': '#2f3638',
        'primary': '#ffb693',
        'tertiary': '#c8c6c5',
        'surface-container-high': '#242b2d',
        'background': '#0e1416',
        'surface-container-highest': '#2f3638',
        'on-surface-variant': '#e2bfb0',
        'outline-variant': '#5a4136',
        'secondary': '#c8c6c5',
        'inverse-primary': '#a04100',
        'inverse-surface': '#dde4e6',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'primary-fixed-dim': '#ffb693',
        'on-tertiary-fixed': '#1c1b1b',
        'on-secondary-fixed': '#1c1b1b',
        'surface-container-low': '#161d1f',
        'primary-fixed': '#ffdbcc',
        'outline': '#a98a7d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '40px',
        margin: '20px',
        xs: '4px',
        md: '24px',
        base: '8px',
        xl: '64px',
        gutter: '16px',
        sm: '12px',
        'stack-lg': '40px',
        'stack-md': '24px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'body-lg': ['Lexend'],
        'headline-md': ['Lexend'],
        'headline-lg': ['Lexend'],
        'display-xl': ['Lexend'],
        'body-md': ['Lexend'],
        'label-bold': ['Lexend'],
        'display-hero': ['Lexend'],
        'data-heavy': ['Lexend'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'data-heavy': ['40px', { lineHeight: '1.0', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};